[package]
name = "chessmASSter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buttplug = "6.0.0"
cozy-chess = "0.3.0"
